### ISSUE TITLE
[ERR 12:50:28.299] Cannot find fx group of that name for decoupler

### ISSUE THREAD

**Issue by ThomasWarChild** [linuxgurugamer/universal-storage-2#10]
I'm reinstalling all my mods 1by1 and these entries pop up in KSP log when I installed Universal Storage II Finalized.

[LOG 12:50:28.296] PartLoader: Compiling Part 'UniversalStorage2/Parts/Science/AdvancedMicroSatWedge/USAdvancedMicroSatWedge'
[ERR 12:50:28.299] Cannot find fx group of that name for decoupler

[ERR 12:50:28.308] Cannot find fx group of that name for decoupler

[LOG 12:50:28.314] PartLoader: Compiling Part 'UniversalStorage2/Parts/Science/BasicMicroSatWedge/USBasicMicroSatWedge'
[ERR 12:50:28.317] Cannot find fx group of that name for decoupler

[ERR 12:50:28.321] Cannot find fx group of that name for decoupler

[LOG 12:50:28.324] PartLoader: Part 'UniversalStorage2/Parts/Science/BasicMicroSatWedge/USBasicMicroSatWedge' has no database record. Creating.
[LOG 12:50:28.326] PartLoader: Compiling Part 'UniversalStorage2/Parts/Science/CargoStorageWedge/USCargoStorageWedge'
[WRN 12:50:28.329] [Part]: Cannot add ModuleCargoPart as this Part 'USCargoStorageWedge' already has a ModuleInventoryPart PartModule and they are mutually exclusive.

**Comment by linuxgurugamer** [comment]
this isn't a support forum, please post on the forums

https://forum.kerbalspaceprogram.com/index.php?/topic/177385-universal-storage-ii-131-and-145-170/
