### ISSUE TITLE
L-ALT experiment has bad crew requirements

### ISSUE THREAD

**Issue by francinum** [linuxgurugamer/universal-storage-2#13]
Requirements mask is:
```
1- VesselControl
4- CrewInPart
```

`CrewInPart` is unsatisfiable as the part cannot hold crew.

https://github.com/linuxgurugamer/universal-storage-2/blob/11ada53387e54cc88aaf10eb5721f1e53d99e6dc/GameData/UniversalStorage2/Parts/Science/MapCamWedge.cfg#L169

**Comment by linuxgurugamer** [comment]
Fixed in next release
