### ISSUE TITLE
Cylindrical shroud string typo: "Retract Brimary Bays" instead of "Retract Primary Bays"

### ISSUE THREAD

**Issue by eminterrupted** [linuxgurugamer/universal-storage-2#5]
Absolutely tiny bug to report, but something I just noticed: some of the cylindrical shroud PAW actions say "Retract Brimary Bays" instead of "Retract Primary Bays." It looks like this loc tag is the culprit:

https://github.com/linuxgurugamer/universal-storage-2/blob/a73f5138e15f2e02e9fedfacc8f34c3db067e0c9/GameData/UniversalStorage2/Localization/en-us.cfg#L47

Example:
![image](https://user-images.githubusercontent.com/22695644/163719134-ee29969f-9a76-4339-9540-97b83b558c18.png)

**Comment by jvosk** [comment]
[Pull request](https://github.com/linuxgurugamer/universal-storage-2/pull/6) submitted
